name: EPIC Issue
description: Create an EPIC that covers a new feature or groups tasks under a certain goal
title: "[EPIC]: "
labels: ["epic"]
projects: ["lonboard", "deck.gl-layers"]
assignees:
  - kylebarron
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What is the driving factor for this EPIC
      placeholder: Describe any relevant background info...
      value: "Describe any relevant background info... (include screenshots as needed)"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Describe the work that we need to do.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance-Criteria
      description: "List the acceptance criteria that need to be completed or artifacts that need to be produced to have this EPIC considered complete."
        value: |
          -
          -
          -
          ...
    validations:
      required: true
